use_frameworks!

platform :ios, '15.0'

target 'BSWHPhotoPicker_Example' do
  pod 'BSWHPhotoPicker', :path => '../'
  pod 'SnapKit'
  pod 'Localize-Swift', '~> 3.2.0'
  pod 'SwiftGen', '~> 6.6.3', :configurations => ['Debug']

  target 'BSWHPhotoPicker_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "15.0"
    end
  end
end
